name: goalzify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+2
  flutter_native_timezone: ^2.0.0
  intl: ^0.19.0
  shared_preferences: ^2.3.0
  time_zone_list: ^1.0.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
