// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAqtlhVI5N_JUNIwdg26rhvZBPnO2Ku70Q",
      authDomain: "goalzify-aa5a6.firebaseapp.com",
      projectId: "goalzify-aa5a6",
      storageBucket: "goalzify-aa5a6.appspot.com",
      messagingSenderId: "1059881546953",
      appId: "1:1059881546953:web:b96f732d27e8cd585c4918");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD77gtNtzrRVZ3V5TSvZ9JED-q1_-2hs-o',
    appId: '1:1059881546953:android:b9a02f1f1ba967a55c4918',
    messagingSenderId: '1059881546953',
    projectId: 'goalzify-aa5a6',
    storageBucket: 'goalzify-aa5a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA4QK9ZTbtxtSJyQf7Y3HBh4cvPXOa9Rw',
    appId: '1:1059881546953:ios:529d2c34ccfbce815c4918',
    messagingSenderId: '1059881546953',
    projectId: 'goalzify-aa5a6',
    storageBucket: 'goalzify-aa5a6.appspot.com',
    iosBundleId: 'com.example.goalzify',
  );
}
